version: "3.7"
services:
    web:
        build:
            context: .
            dockerfile: ./.docker/dockerfile
        ports:
            - 3500:80
        volumes:
            - ./app:/project
            - ./conf:/etc/apache2/sites-available
            - ./conf:/etc/apache2/sites-enabled 
    db:
        image: mariadb
        restart: always
        depends_on:
            - web
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: enigma
            MYSQL_USER: enigma
            MYSQL_PASSWORD: root
        ports:
            - 3600:3800
